spring.datasource.url=jdbc:postgresql://dpg-d6rdebcr85hc73fasvn0-a.oregon-postgres.render.com:5432/school_db_kybo
spring.datasource.username=postgres
spring.datasource.password=Deusmeu19

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}